name: inventario_especies_gc

channels:
  - conda-forge
  - anaconda
  - r
  - bioconda
  - defaults

dependencies:
  - bash=5.2.21
  - coreutils=9.5
  - python=3.12.8
  - pandas=2.2.3
  - numpy=2.2.1
  - great_tables=0.15.0
  - plotnine=0.14.4
  - r-base=4.3.3
  - r-tidyverse=2.0.0
  - ipykernel=6.29.5
  - jupyter=1.1.1
  - rpy2=3.5.11
  - jupyter_contrib_nbextensions=0.7.0
  - unidecode=1.3.8
  - snakemake=8.26.0